/**
 * §9.3 P5.4 source request contract wiring.
 *
 * Each business source (conversation/letter_reply/incoming_letter/battle/bookmark)
 * is wired to TransitionJournalApi.beginTransition with the source-specific
 * requestKey + commitMode, then to resolveTimelineStrict + v2 store writes.
 *
 * v1 getOrCreateChild eventKey dedup is no longer used for NEW records; the
 * journal API creates TimelineNodeV2 entries with transitionAttemptId linkage.
 *
 * Two commit modes use shared guard helpers:
 *   - `post-bump-node-only`: compares target epoch/current token, only fills
 *     in node/parent. Used by letter_reply, incoming_letter, battle.
 *   - `atomic-advance`: compares observed epoch/node/current token and target
 *     pending token, then advances epoch + consumes pending + writes target
 *     node/graph parent in one shot. Used by conversation.
 *
 * Both helpers first do source-appropriate identity/request/delivery guard,
 * and accept the target node as already-applied (so terminal attempts with
 * CK3 == target become idempotent updates rather than new attempts).
 */
import type { CampaignPlayerIdentity } from '../shared/gameData/CampaignIdentity.js';
import {
    FsTimelinePersistence,
    TimelineRegistry,
    TimelineRegistryCorruptError,
    type GameDataLike,
    type TimelineContext,
    type SourceKind,
    type CreateChildNodeResult,
    buildContextFromGameData,
    resolveTimelineContext,
    generateNodeId,
    formatNodeId,
    buildCheckpointSetEffect
} from './timelineManager.js';
import {
    TransitionJournalApi
} from './timelineJournalApi.js';
import { createHash } from 'crypto';
import {
    TransitionJournalStore,
    type ObservedSnapshot,
    type TransitionCommitMode,
    type SourceKind as JournalSourceKind
} from './timelineTransitionJournal.js';
import {
    resolveTimelineStrict
} from './timelineResolver.js';
import { withTimelineLock } from './timelineLock.js';
import {
    loadCampaignStoreWithMigration,
    observedStateFromContext
} from './campaignBusiness.js';
import type { MigrationStageOptions } from './campaignMigration.js';

export type { SourceKind } from './timelineManager.js';

/**
 * Output of every source's transition. The journal API creates a target
 * node with transitionAttemptId linkage; the run script is generated using
 * the existing buildCheckpointSetEffect helper so the mod-side bump behavior
 * is preserved.
 */
export interface SourceTransitionResult {
    attemptId: string;
    source: SourceKind;
    requestKey: string;
    commitMode: TransitionCommitMode;
    targetNodeId: string;
    reused: boolean;
    phase: string;
    /**
     * The CK3 run script that bumps the checkpoint to the target node.
     * Empty for record-only sources (bookmark).
     */
    script: string;
    /**
     * The parent context for downstream chaining (battle batch).
     */
    context: TimelineContext;
    /**
     * Set by record-only sources; false for checkpoint transitions.
     */
    recorded?: boolean;
    /**
     * The current node id the record was attached to (record-only sources).
     */
    currentNodeId?: string;
}

// ───────────────────────────────────────────────────────────────────────
// Shared guard helpers for the two commit modes.
// ───────────────────────────────────────────────────────────────────────

export interface CommitGuardInput {
    /**
     * The observed CK3 state captured at operation start (the snapshot the
     * App received, including epoch/node/token).
     */
    observed: ObservedSnapshot;
    /**
     * The resolved parent node id (graph parent) for the target node.
     */
    graphParentNodeId: string | null;
    /**
     * The target epoch the run script will write.
     */
    targetEpoch: number;
    /**
     * The target node id (generated by the caller, stable for the attempt).
     */
    targetNodeId: string;
    /**
     * Optional pending checkpoint token forwarded to the target node
     * (atomic-advance mode).
     */
    targetCorrelationToken?: number;
}

/**
 * §9.3 `post-bump-node-only` guard: the mod has already bumped the
 * checkpoint epoch before the App runs. The guard only compares the
 * target epoch and (when present) the current token; it accepts the
 * target node as already-applied when CK3 == target.
 *
 * Used by letter_reply, incoming_letter, battle.
 */
export function guardPostBumpNodeOnly(input: CommitGuardInput): {
    ok: boolean;
    reason?: string;
} {
    if (typeof input.targetEpoch !== 'number' || !Number.isFinite(input.targetEpoch) || input.targetEpoch < 0) {
        return { ok: false, reason: 'post-bump-node-only: targetEpoch must be a non-negative integer' };
    }
    if (!input.targetNodeId || input.targetNodeId.indexOf('-') <= 0) {
        return { ok: false, reason: 'post-bump-node-only: targetNodeId is invalid' };
    }
    // The caller has already produced the target node id; the guard accepts
    // the target as already-applied via the journal's classifyReconciliation
    // (idempotent-update when terminalEvidence + CK3 == target).
    return { ok: true };
}

/**
 * §9.3 `atomic-advance` guard: the App must compare the observed epoch /
 * node / current token AND the target pending token before advancing the
 * epoch, consuming the pending token, and writing the target node/graph
 * parent in one shot.
 *
 * Used by conversation.
 */
export function guardAtomicAdvance(input: CommitGuardInput): {
    ok: boolean;
    reason?: string;
} {
    const base = guardPostBumpNodeOnly(input);
    if (!base.ok) return base;
    // Atomic-advance additionally requires the observed state to carry an
    // epoch (so we can prove the CK3 snapshot is at the pre-bump state).
    if (typeof input.observed.epoch !== 'number' || input.observed.epoch < 0) {
        return { ok: false, reason: 'atomic-advance: observed.epoch is required' };
    }
    // Pending token is optional for legacy mods but, when present, must be
    // a positive integer (the mod preallocated it for the next checkpoint).
    if (input.targetCorrelationToken !== undefined) {
        if (typeof input.targetCorrelationToken !== 'number'
            || !Number.isInteger(input.targetCorrelationToken)
            || input.targetCorrelationToken <= 0) {
            return { ok: false, reason: 'atomic-advance: targetCorrelationToken must be a positive integer when present' };
        }
    }
    return { ok: true };
}

// ───────────────────────────────────────────────────────────────────────
// Shared begin/commit helper.
// ───────────────────────────────────────────────────────────────────────

/**
 * Common entry point: load the campaign-scoped store (with migration),
 * construct the journal API, run the beginTransition with the source's
 * requestKey + commitMode, then build the run script. The run script is
 * built unconditionally (even on reused attempts) so the mod receives the
 * checkpoint bump command; for a reused attempt the bump is idempotent
 * (sets the same target values), which is harmless and keeps the caller
 * path uniform.
 */
async function runSourceTransition(args: {
    userDataDir: string;
    identity: CampaignPlayerIdentity;
    gameData: GameDataLike;
    source: SourceKind;
    requestKey: string;
    eventSignature: string;
    commitMode: TransitionCommitMode;
    targetEpoch: number;
    scopeVar: string;
    guard: (input: CommitGuardInput) => { ok: boolean; reason?: string };
    observedState?: MigrationStageOptions['observedState'];
}): Promise<SourceTransitionResult> {
    return withTimelineLock(
        args.userDataDir,
        { campaignId: args.identity.campaignId, playerId: args.identity.playerId },
        async () => {
            const persistence = new FsTimelinePersistence(args.userDataDir);
            const observedContext = buildContextFromGameData(args.gameData);
            const observedState = args.observedState ?? observedStateFromContext(observedContext);
            const migrationResult = loadCampaignStoreWithMigration(args.userDataDir, args.identity, {
                observedState
            });
            const loadResult = migrationResult.loadResult;
            let registry: TimelineRegistry;
            if (loadResult.status === 'found') {
                registry = loadResult.store;
            } else if (loadResult.status === 'missing') {
                registry = new TimelineRegistry(args.identity.playerId);
            } else {
                throw new TimelineRegistryCorruptError(
                    loadResult.filePath,
                    'campaign registry corrupt on business-entry load',
                    loadResult.quarantinePath,
                    loadResult.errors
                );
            }
            // Strict resolver: identify the current node for graph-parent
            // resolution. resolveTimelineContext flattens back into a
            // TimelineContext; if non-resolved, the snapshot's node is
            // preserved (caller will fail-closed downstream if absent).
            const parentContext = resolveTimelineContext(registry, observedContext);
            const graphParentNodeId = parentContext.timelineNodeId ?? null;
            // Build observed snapshot for the journal API.
            const observed: ObservedSnapshot = {
                epoch: observedContext.checkpointEpoch,
                nodeA: observedContext.timelineNodeId ? Number(observedContext.timelineNodeId.split('-')[0]) : undefined,
                nodeB: observedContext.timelineNodeId ? Number(observedContext.timelineNodeId.split('-')[1]) : undefined,
                checkpointToken: observedContext.checkpointToken,
                pendingCheckpointToken: observedContext.pendingCheckpointToken
            };
            // Generate a stable target node id (deterministic per attempt;
            // the journal store will reject collisions via validateNodeV2).
            // On reuse, the journal API returns the existing target node id
            // from the existing entry, so the caller observes the same
            // targetNodeId for the same logical request.
            // Rehydrate the v2 journal store from the loaded envelope (or
            // start fresh if the envelope had no v2 payload).
            const store = new TransitionJournalStore(loadResult.status === 'found' ? loadResult.v2 : undefined);
            const existingEntry = store.findLiveAttemptByRequestKey(
                args.source as JournalSourceKind,
                args.requestKey
            );
            const targetNodeId = existingEntry?.targetNodeId ?? generateTargetNodeId();
            const targetCorrelationToken = observedContext.pendingCheckpointToken;
            const guardInput: CommitGuardInput = {
                observed,
                graphParentNodeId,
                targetEpoch: args.targetEpoch,
                targetNodeId,
                targetCorrelationToken
            };
            const guardResult = args.guard(guardInput);
            if (!guardResult.ok) {
                throw new Error(`timelineBusinessWire: guard rejected transition: ${guardResult.reason ?? 'unknown'}`);
            }
            const api = new TransitionJournalApi({
                store,
                persistence,
                identity: args.identity,
                registry
            });
            const attempt = api.beginTransition({
                snapshot: observed,
                source: args.source as JournalSourceKind,
                requestKey: args.requestKey,
                eventSignature: args.eventSignature,
                targetNodeId,
                targetEpoch: args.targetEpoch,
                commitMode: args.commitMode,
                graphParentNodeId,
                targetCorrelationToken
            });
            // Advance to store-committed (the registry v1 + v2 envelope is
            // persisted atomically inside commitTimelineStoreAttempt).
            api.commitTimelineStoreAttempt(attempt);
            // Build the run script that bumps the checkpoint. The run
            // script's identity fields are derived from the target node +
            // graph parent; both are stable per attempt.
            const script = buildCheckpointSetEffect(
                targetNodeId,
                graphParentNodeId,
                args.targetEpoch,
                args.scopeVar,
                targetCorrelationToken
            );
            const resultContext: TimelineContext = {
                playerId: args.identity.playerId,
                checkpointEpoch: args.targetEpoch,
                checkpointToken: targetCorrelationToken,
                timelineNodeId: targetNodeId,
                timelineParentId: graphParentNodeId ?? undefined
            };
            return {
                attemptId: attempt.attemptId,
                source: args.source,
                requestKey: args.requestKey,
                commitMode: args.commitMode,
                targetNodeId,
                reused: attempt.reused,
                phase: attempt.phase,
                script,
                context: resultContext
            };
        }
    );
}

function generateTargetNodeId(): string {
    // Generate a fresh node id for the target. Reuse the existing helper so
    // the format matches the rest of the system.
    return formatNodeId(generateNodeId());
}

// ───────────────────────────────────────────────────────────────────────
// Conversation source: atomic-advance + UUID requestKey.
// ───────────────────────────────────────────────────────────────────────

export interface ConversationTransitionInput {
    userDataDir: string;
    gameData: GameDataLike;
    identity: CampaignPlayerIdentity;
    /**
     * App-generated UUID for this close request. Same UUID is reused for
     * all retries of the same close. A new close after terminalEvidence
     * generates a new UUID.
     */
    requestKey: string;
    /**
     * Event signature (conv:playerID_aiID_date_epoch). Stored on the v2
     * node for audit; NOT used as the requestKey.
     */
    eventSignature: string;
    targetEpoch: number;
    scopeVar: string;
}

export async function runConversationTimelineTransition(
    input: ConversationTransitionInput
): Promise<SourceTransitionResult> {
    return runSourceTransition({
        userDataDir: input.userDataDir,
        identity: input.identity,
        gameData: input.gameData,
        source: 'conversation',
        requestKey: input.requestKey,
        eventSignature: input.eventSignature,
        commitMode: 'atomic-advance',
        targetEpoch: input.targetEpoch,
        scopeVar: input.scopeVar,
        guard: guardAtomicAdvance
    });
}

// ───────────────────────────────────────────────────────────────────────
// Letter reply source: post-bump-node-only + slot+letterDeliveryId.
// ───────────────────────────────────────────────────────────────────────

export interface LetterReplyTransitionInput {
    userDataDir: string;
    gameData: GameDataLike;
    identity: CampaignPlayerIdentity;
    slotId: string;
    letterDeliveryId: number;
    eventSignature: string;
    targetEpoch: number;
    scopeVar: string;
}

function occurrenceSignatureSuffix(eventSignature: string): string {
    // A delivery id lives in the CK3 save, so it is deliberately reused after
    // a rollback.  Keep the persisted request key compact while adding the
    // event identity that distinguishes two different deliveries occupying the
    // same post-rollback slot.
    return createHash('sha256').update(eventSignature, 'utf8').digest('hex').slice(0, 16);
}

export function letterReplyRequestKey(slotId: string, letterDeliveryId: number, eventSignature?: string): string {
    const base = `${slotId}|${letterDeliveryId}`;
    return eventSignature ? `${base}|${occurrenceSignatureSuffix(eventSignature)}` : base;
}

export async function runLetterReplyTimelineTransition(
    input: LetterReplyTransitionInput
): Promise<SourceTransitionResult> {
    const requestKey = letterReplyRequestKey(input.slotId, input.letterDeliveryId, input.eventSignature);
    return runSourceTransition({
        userDataDir: input.userDataDir,
        identity: input.identity,
        gameData: input.gameData,
        source: 'letter_reply',
        requestKey,
        eventSignature: input.eventSignature,
        commitMode: 'post-bump-node-only',
        targetEpoch: input.targetEpoch,
        scopeVar: input.scopeVar,
        guard: guardPostBumpNodeOnly
    });
}

// ───────────────────────────────────────────────────────────────────────
// Incoming letter source: post-bump-node-only + slot+type+deliveryId.
// ───────────────────────────────────────────────────────────────────────

export interface IncomingLetterTransitionInput {
    userDataDir: string;
    gameData: GameDataLike;
    identity: CampaignPlayerIdentity;
    slotId: string;
    type: string;
    deliveryId: number;
    eventSignature: string;
    targetEpoch: number;
    scopeVar: string;
}

export function incomingLetterRequestKey(slotId: string, type: string, deliveryId: number, eventSignature?: string): string {
    const base = `${slotId}|${type}|${deliveryId}`;
    return eventSignature ? `${base}|${occurrenceSignatureSuffix(eventSignature)}` : base;
}

export async function runIncomingLetterTimelineTransition(
    input: IncomingLetterTransitionInput
): Promise<SourceTransitionResult> {
    const requestKey = incomingLetterRequestKey(input.slotId, input.type, input.deliveryId, input.eventSignature);
    return runSourceTransition({
        userDataDir: input.userDataDir,
        identity: input.identity,
        gameData: input.gameData,
        source: 'incoming_letter',
        requestKey,
        eventSignature: input.eventSignature,
        commitMode: 'post-bump-node-only',
        targetEpoch: input.targetEpoch,
        scopeVar: input.scopeVar,
        guard: guardPostBumpNodeOnly
    });
}

// ───────────────────────────────────────────────────────────────────────
// Battle source: post-bump-node-only + slot+battleDeliveryId.
// Multiple battles per batch chain off the previous battle's context.
// ───────────────────────────────────────────────────────────────────────

export interface BattleBatchTransitionEntry {
    /**
     * The battle facts signature (slot|playerId|date|location|...). Stored
     * as eventSignature on the v2 node; NOT used as requestKey.
     */
    eventSignature: string;
    slotId: string;
    /**
     * Mod-provided battle delivery id (occurrence evidence). Combined with
     * slotId to form the requestKey.
     */
    battleDeliveryId: string;
    context: TimelineContext;
    nextEpoch: number | undefined;
}

export interface BattleBatchTransitionInput {
    userDataDir: string;
    gameData: GameDataLike;
    identity: CampaignPlayerIdentity;
    entries: BattleBatchTransitionEntry[];
}

export interface BattleBatchTransitionResult {
    timelines: Map<string, SourceTransitionResult>;
}

export function battleRequestKey(slotId: string, battleDeliveryId: string): string {
    return `${slotId}|${battleDeliveryId}`;
}

export async function runBattleTimelineBatchTransition(
    input: BattleBatchTransitionInput
): Promise<BattleBatchTransitionResult> {
    return withTimelineLock(
        input.userDataDir,
        { campaignId: input.identity.campaignId, playerId: input.identity.playerId },
        async () => {
            const persistence = new FsTimelinePersistence(input.userDataDir);
            const firstContext = input.entries[0]?.context ?? { playerId: input.identity.playerId };
            const observedState = observedStateFromContext(firstContext);
            const migrationResult = loadCampaignStoreWithMigration(input.userDataDir, input.identity, {
                observedState
            });
            const loadResult = migrationResult.loadResult;
            let registry: TimelineRegistry;
            if (loadResult.status === 'found') {
                registry = loadResult.store;
            } else if (loadResult.status === 'missing') {
                registry = new TimelineRegistry(input.identity.playerId);
            } else {
                throw new TimelineRegistryCorruptError(
                    loadResult.filePath,
                    'campaign registry corrupt on battle-report load',
                    loadResult.quarantinePath,
                    loadResult.errors
                );
            }
            const store = new TransitionJournalStore(loadResult.status === 'found' ? loadResult.v2 : undefined);
            const api = new TransitionJournalApi({
                store,
                persistence,
                identity: input.identity,
                registry
            });
            const timelines = new Map<string, SourceTransitionResult>();
            let chainedContext: TimelineContext | undefined;
            let previousSnapshotKey: string | undefined;
            for (const entry of input.entries) {
                const snapshotContext = resolveTimelineContext(registry, entry.context);
                const snapshotKey = [
                    snapshotContext.timelineNodeId ?? '',
                    snapshotContext.checkpointEpoch ?? '',
                    snapshotContext.checkpointToken ?? '',
                    snapshotContext.pendingCheckpointToken ?? ''
                ].join('\u001f');
                const parentContext = previousSnapshotKey === snapshotKey && chainedContext
                    ? chainedContext
                    : snapshotContext;
                const nextEpoch = previousSnapshotKey === snapshotKey
                    && parentContext.checkpointEpoch !== undefined
                    ? Math.max(entry.nextEpoch ?? parentContext.checkpointEpoch + 1, parentContext.checkpointEpoch + 1)
                    : entry.nextEpoch;
                const graphParentNodeId = parentContext.timelineNodeId ?? null;
                const observed: ObservedSnapshot = {
                    epoch: parentContext.checkpointEpoch,
                    nodeA: parentContext.timelineNodeId ? Number(parentContext.timelineNodeId.split('-')[0]) : undefined,
                    nodeB: parentContext.timelineNodeId ? Number(parentContext.timelineNodeId.split('-')[1]) : undefined,
                    checkpointToken: parentContext.checkpointToken,
                    pendingCheckpointToken: parentContext.pendingCheckpointToken
                };
                const requestKey = battleRequestKey(entry.slotId, entry.battleDeliveryId);
                const targetNodeId = (() => {
                    const existingBattle = store.findLiveAttemptByRequestKey(
                        'battle',
                        requestKey
                    );
                    return existingBattle?.targetNodeId ?? generateTargetNodeId();
                })();
                const targetCorrelationToken = parentContext.pendingCheckpointToken;
                const resolvedNextEpoch = nextEpoch ?? (parentContext.checkpointEpoch !== undefined ? parentContext.checkpointEpoch + 1 : 0);
                const guardInput: CommitGuardInput = {
                    observed,
                    graphParentNodeId,
                    targetEpoch: resolvedNextEpoch,
                    targetNodeId,
                    targetCorrelationToken
                };
                const guardResult = guardPostBumpNodeOnly(guardInput);
                if (!guardResult.ok) {
                    throw new Error(`timelineBusinessWire.battle: guard rejected transition: ${guardResult.reason ?? 'unknown'}`);
                }
                const attempt = api.beginTransition({
                    snapshot: observed,
                    source: 'battle',
                    requestKey,
                    eventSignature: entry.eventSignature,
                    targetNodeId,
                    targetEpoch: resolvedNextEpoch,
                    commitMode: 'post-bump-node-only',
                    graphParentNodeId,
                    targetCorrelationToken
                });
                api.commitTimelineStoreAttempt(attempt);
                const script = buildCheckpointSetEffect(
                    targetNodeId,
                    graphParentNodeId,
                    resolvedNextEpoch,
                    'votc_battle_report_player',
                    targetCorrelationToken
                );
                const resultContext: TimelineContext = {
                    playerId: input.identity.playerId,
                    checkpointEpoch: resolvedNextEpoch,
                    checkpointToken: targetCorrelationToken,
                    timelineNodeId: targetNodeId,
                    timelineParentId: graphParentNodeId ?? undefined
                };
                timelines.set(entry.eventSignature, {
                    attemptId: attempt.attemptId,
                    source: 'battle',
                    requestKey,
                    commitMode: 'post-bump-node-only',
                    targetNodeId,
                    reused: attempt.reused,
                    phase: attempt.phase,
                    script,
                    context: resultContext
                });
                previousSnapshotKey = snapshotKey;
                chainedContext = resultContext;
            }
            return { timelines };
        }
    );
}

// ───────────────────────────────────────────────────────────────────────
// Bookmark source: record-only (no checkpoint transition).
// ───────────────────────────────────────────────────────────────────────

export interface BookmarkImportInput {
    userDataDir: string;
    gameData: GameDataLike;
    identity: CampaignPlayerIdentity;
    /**
     * Idempotent import id (caller-generated). Re-importing with the same
     * id is a no-op.
     */
    importId: string;
}

export interface BookmarkImportResult {
    /**
     * Current node id resolved by strict resolver.
     */
    currentNodeId: string | undefined;
    /**
     * True if this call wrote a new record; false if the import id was
     * already present (idempotent).
     */
    recorded: boolean;
}

/**
 * Record-only: bookmark imports do NOT create a checkpoint transition.
 * Instead, they attach an idempotent import record to the current node
 * resolved by resolveTimelineStrict.
 *
 * The current implementation stores the import id on the v2 node's
 * `eventSignature` field (prefixed with `bookmark:`) so a re-import with
 * the same import id is detected and skipped. Phase 8 will replace this
 * with the summary-override machinery.
 */
export async function recordBookmarkImport(
    input: BookmarkImportInput
): Promise<BookmarkImportResult> {
    return withTimelineLock(
        input.userDataDir,
        { campaignId: input.identity.campaignId, playerId: input.identity.playerId },
        async () => {
            const persistence = new FsTimelinePersistence(input.userDataDir);
            const observedContext = buildContextFromGameData(input.gameData);
            const observedState = observedStateFromContext(observedContext);
            const migrationResult = loadCampaignStoreWithMigration(input.userDataDir, input.identity, {
                observedState
            });
            const loadResult = migrationResult.loadResult;
            let registry: TimelineRegistry;
            if (loadResult.status === 'found') {
                registry = loadResult.store;
            } else if (loadResult.status === 'missing') {
                registry = new TimelineRegistry(input.identity.playerId);
            } else {
                throw new TimelineRegistryCorruptError(
                    loadResult.filePath,
                    'campaign registry corrupt on bookmark-import load',
                    loadResult.quarantinePath,
                    loadResult.errors
                );
            }
            // Use the strict resolver to identify the current node.
            const resolution = resolveTimelineStrict({ registry, context: observedContext });
            const currentNodeId = resolution.status === 'resolved' ? resolution.context.timelineNodeId : observedContext.timelineNodeId;
            if (!currentNodeId) {
                // No current node: cannot attach the import record. Return
                // a non-recorded result so the caller knows the import was
                // a no-op (Phase 8 will introduce summary-override nodes
                // that do not require a current node).
                return { currentNodeId: undefined, recorded: false };
            }
            const store = new TransitionJournalStore(loadResult.status === 'found' ? loadResult.v2 : undefined);
            // Idempotency: scan the v2 nodes for an existing import record
            // with this import id. We store the import id on the node's
            // eventSignature (prefixed) so we can detect duplicates without
            // a separate index.
            const importSignature = `bookmark:${input.importId}`;
            const existing = store.getAllNodes().find(n => n.eventSignature === importSignature);
            if (existing) {
                // Idempotent: the same import id has already been recorded.
                persistence.saveStoreWithIdentity(input.identity, registry, store.serialize());
                return { currentNodeId, recorded: false };
            }
            // Record-only: we do NOT create a transition attempt. We
            // attach the import record to the current node by adding a
            // dedicated v2 node whose parent is the current node. The v2
            // node schema requires a non-empty transitionAttemptId, so we
            // use the `bookmark:<importId>` sentinel to mark record-only
            // nodes (no journal entry is created for this id). The import
            // id is also stored as eventSignature so future imports can
            // detect duplicates.
            const importNodeId = generateTargetNodeId();
            const now = new Date().toISOString();
            store.upsertNode(importNodeId, {
                parentId: currentNodeId,
                epoch: observedContext.checkpointEpoch ?? 0,
                source: 'summary_manual',
                transitionAttemptId: `bookmark:${input.importId}`,
                requestKey: input.importId,
                eventSignature: importSignature,
                createdAt: now
            });
            persistence.saveStoreWithIdentity(input.identity, registry, store.serialize());
            return { currentNodeId, recorded: true };
        }
    );
}

// ───────────────────────────────────────────────────────────────────────
// Migration preview: uses the legacy epoch-heuristic resolver
// (resolveTimelineContextLegacy). Exported here so callers can route
// migration-preview requests through the legacy resolver without pulling
// in timelineManager directly.
// ───────────────────────────────────────────────────────────────────────

export { resolveTimelineContextLegacy } from './timelineManager.js';
