name: Publish Electron App

on:
  workflow_dispatch:  # 👈 manual trigger
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ${{ matrix.os }}
    environment: prod

    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    - name: Publish application
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}
      run: npm run publish
